language: node_js

node_js:
- 13

services:
- docker

# Prétester les installations
install:
- npm install

# Scripts à exécuter en guise de tests
before_script:
- echo "no tests"

script:
- echo "Udacity - Week $UDACITY_WEEK"
- docker --version # print the version for logging
- docker build -t connect-session .
- docker tag connect-session $DOCKER_USERNAME/connect-session:latest

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push abdelino/connect-session:latest